{{if .Values.wordpress.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.wordpress.deployment.name }}-secret-{{ .Values.wordpress.deployment.version| replace "." "-" }}
  labels:
    app: {{ .Values.wordpress.deployment.name }}
    version: {{ .Values.wordpress.deployment.version | quote }}
    environment: {{ .Values.wordpress.deployment.environment }}
type: Opaque
data:
  {{- toYaml .Values.wordpress.secret.data | nindent 2 }}
{{ end }}