{{ if .Values.wordpress.serviceaccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.wordpress.deployment.name }}-serviceaccount-{{ .Values.wordpress.deployment.version| replace "." "-" }}
  {{ if .Values.wordpress.serviceaccount.annotations }}
  annotations:
    {{- toYaml .Values.wordpress.serviceaccount.annotations | nindent 4 }}
  {{- end }}
  labels:
    app: {{ .Values.wordpress.deployment.name }}
    environment: {{ .Values.wordpress.deployment.environment }}
{{- end }}
